apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: orders-api
spec:
  project: dev
  source:
    path: guestbook
    repoURL: https://github.com/argoproj/argocd-example-apps.git
  destination:
    namespace: orders
    server: https://kubernetes.default.svc
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-app
spec:
  project: dev
  source:
    directory:
      jsonnet:
        tlas:
          - name: ""
            value: ""
    path: attacking-argo-cd-with-argo-cd/bootstrap-attack
    repoURL: https://github.com/crenshaw-dev/argocon-22.git
  destination:
    namespace: default
    server: https://kubernetes.default.svc
