apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
data:
  policy.csv: |
    g, mcrenshaw-org, dev
    p, dev, applications, get,  dev/*, allow
    p, dev, applications, sync, dev/*, allow

